library(shinytest2)

test_that("{shinytest2} recording: app_arcenso", {
  local_app_support(test_path("../../inst/app_arcenso"))
  app <- AppDriver$new(test_path("../../inst/app_arcenso"), variant = platform_variant(),
      name = "app_arcenso", seed = 0, height = 738, width = 1235)
  app$set_inputs(tablacensal = character(0), timeout_ = 10000)
  app$set_inputs(geo = "10", timeout_ = 10000)
  app$set_inputs(tema = "conyugal", timeout_ = 10000)
  app$set_inputs(tema = "fecundidad", timeout_ = 10000)
  app$set_inputs(geo = "00", timeout_ = 10000)
  app$set_inputs(anio = "1980", timeout_ = 10000)
  app$set_inputs(tema = "educacion", timeout_ = 10000)
  app$set_inputs(tema = "actividad", timeout_ = 10000)
  app$set_inputs(tema = "vivienda", timeout_ = 10000)
  app$set_inputs(anio = "1970", timeout_ = 10000)
  app$set_inputs(geo = "14", timeout_ = 10000)
  app$set_inputs(geo = "18", timeout_ = 10000)
  app$set_inputs(geo = "26", timeout_ = 10000)
  app$set_inputs(geo = "14", timeout_ = 10000)
  app$set_inputs(tema = "habitacional", timeout_ = 10000)
  app$set_inputs(geo = "30", timeout_ = 10000)
  app$set_inputs(tema = "composicion", timeout_ = 10000)
  app$expect_values()
  app$set_inputs(tema = "educacion", timeout_ = 10000)
  app$set_inputs(listas = "Cuadro 4. Provincia de Entre Ríos. Población de 5 y más años, por grupo de edad, según asistencia escolar. Año 1970", timeout_ = 10000)
})
